include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.db_model.dart"
    - "lib/models/**"
    - "db_model_generator/**"
    - "lib/amplifyconfiguration.dart"