builders:
  db_model_generator:db_model_factory:
    # library URI containing the builder - maps to `lib/member_count_library_generator.dart`
    import: "package:db_model_generator/db_model_generator.dart"
    # Name of the function in the above library to call.
    builder_factories: ["dbModelLibraryBuilder"]
    # The mapping from the source extension to the generated file extension
    build_extensions: {".dart": [".db_model.dart"]}
    # Will automatically run on any package that depends on it
    auto_apply: dependents
    # Generate the output directly into the package, not to a hidden cache dir
    build_to: source

targets:
  $default:
    builders:
      json_serializable:
        options:
          # Options configure how source code is generated for every
          # `@JsonSerializable`-annotated class in the package.
          #
          # The default value for each is listed.
          any_map: false
          checked: false
          constructor: ""
          create_factory: true
          create_field_map: false
          create_per_field_to_json: false
          create_to_json: true
          disallow_unrecognized_keys: false
          explicit_to_json: true
          field_rename: none
          generic_argument_factories: false
          ignore_unannotated: false
          include_if_null: true # this setting is highly important, as GraphQL has to know all the possible fields
      
      db_model_generator|db_model_factory:
        generate_for:
          - lib/backend/callableModels/*.dart



      