name: mobile_app
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

    


  #amplify packages
  amplify_flutter: ^0.4.0-rc.1
  amplify_datastore: ^0.4.0-rc.1
  amplify_api: ^0.4.0-rc.1
  amplify_auth_cognito: ^0.4.0-rc.1


  font_awesome_flutter: ^9.2.0
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.0.1
  image_picker: ^0.8.4+10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  assets:
      - assets/test/
      - assets/fixAssets/