name: mobile_app
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.01+2

environment:
  sdk: ">=2.15.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  string_similarity: ^2.0.0

    


  #amplify packages
  amplify_flutter: ^0.6.10
  #amplify_datastore: ^0.6.10
  amplify_api: ^0.6.10
  amplify_auth_cognito: ^0.6.10
  amplify_storage_s3: ^0.6.10

  
  #advance_pdf_viewer_fork: ^2.0.0

  


  font_awesome_flutter: ^9.2.0
  cupertino_icons: ^1.0.2
  material_design_icons_flutter: ^5.0.6595
  flutter_bloc: ^8.0.1
  flutter_sound: ^8.3.9
  path_provider: ^2.0.9
  path: ^1.8.0
  image_picker: ^0.8.4+10
  dropdown_search: ^5.0.6
  permission_handler: ^9.2.0
  hive: ^2.1.0
  connectivity_plus: ^4.0.2
  flutter_rating_bar: ^4.0.0
  isolate_image_compress: ^1.0.0

  lazy_load_scrollview: ^1.3.0

  geolocator: ^8.2.1
  flutter_dotenv: ^5.0.2
  sembast: ^3.4.0+6
  synchronized: ^3.0.1
  graphql_flutter: ^5.1.2
  json_annotation: ^4.8.0
  gql: ^1.0.0
  graphql: ^5.1.3
  db_model_generator:
    path: db_model_generator/



dev_dependencies:
  build_runner: ^2.3.3
  source_gen: ^1.2.7
  json_serializable: ^6.6.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/fixAssets/app_icon.png"

flutter:
  uses-material-design: true

  assets:
      - assets/fixAssets/
      - assets/specificAssets/
      - .env
#      - db_model_generator.dart