name: mobile_app
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

    


  #amplify packages
  amplify_flutter: ^0.3.0-rc.2
  amplify_datastore: ^0.3.0-rc.3
  amplify_api: ^0.3.0-rc.3
  amplify_auth_cognito: ^0.3.0-rc.3

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  assets:
      - assets/test/