# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    environment:
      name: cicd
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: lib/cicd/node/

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: lib/cicd/node/package-lock.json
      - name: main
        env:
          DUMMY: ${{ secrets.DUMMY }}
        run: |
          npm ci
          node release.mjs "$DUMMY"
