name: deploy-to-production

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: lib/cicd/node/deploy/package-lock.json
      - name: main
        env:
          APOLAT2000PERSONALACCESSTOKEN: ${{ secrets.APOLAT2000PERSONALACCESSTOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: |
          npm --prefix lib/cicd/node/deploy ci
          npm install -g @aws-amplify/cli
          res=$(npm --prefix lib/cicd/node/deploy run label-check -- prod "$APOLAT2000PERSONALACCESSTOKEN" "$AWS_ACCESS_KEY_ID" "$AWS_SECRET_ACCESS_KEY" "$AWS_DEFAULT_REGION" | tail -1) && bash ./lib/cicd/node/deploy/deploy.sh $res
          
